services:
  app:
    build: .
    container_name: laravel_app
    image: test-task/laravelapp:1.0.1
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network


  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER=${DB_USERNAME}
      POSTGRES_PASSWORD=${DB_PASSWORD}
      POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: {}
